name: update-assets

on:
  schedule:
    - cron: 00 09 * * *

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v2'

    - name: show content of build file
      working-directory: assets
      run: pwd && head -2 dbatools-buildref-index.json
    
    - name: Pull build ref file from dbatools
      working-directory: assets
      run: curl -O https://raw.githubusercontent.com/sqlcollaborative/dbatools/development/bin/dbatools-buildref-index.json
    
    - name: show content of build file
      working-directory: assets
      run: head -2 dbatools-buildref-index.json
    
    - name: commit if file changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: updating build ref file

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  updateindex:
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
    
      - name: Pull index file from dbatools
        working-directory: assets
        run: curl -O https://raw.githubusercontent.com/sqlcollaborative/dbatools/development/bin/dbatools-buildref-index.json
      
      - name: commit if file changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updating build ref file
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
